// <auto-generated />
using System;
using LuckyPaw.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LuckyPaw.Migrations
{
    [DbContext(typeof(LuckyPawContext))]
    partial class LuckyPawContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LuckyPaw.Models.CartItemModel", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CartQty");

                    b.Property<double>("PricePuppy");

                    b.Property<string>("PricePuppyDesc");

                    b.Property<int>("PricePuppyID");

                    b.Property<double>("PriceTraining");

                    b.Property<string>("TrainingName");

                    b.Property<int>("TrainingServicesPriceID");

                    b.HasKey("CartId");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("LuckyPaw.Models.LoginModel", b =>
                {
                    b.Property<int>("LoginID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("LoginID");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("LuckyPaw.Models.PricingPuppyModel", b =>
                {
                    b.Property<int>("PricePuppyID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("PricePuppy");

                    b.Property<string>("PricePuppyDesc");

                    b.Property<string>("PricePuppyImageUrl");

                    b.Property<int>("PuppyQty");

                    b.HasKey("PricePuppyID");

                    b.ToTable("PricePuppy");
                });

            modelBuilder.Entity("LuckyPaw.Models.RegistrationModel", b =>
                {
                    b.Property<int>("RegistrationID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("State");

                    b.Property<string>("UserName");

                    b.Property<string>("ZipCode");

                    b.HasKey("RegistrationID");

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("LuckyPaw.Models.TrainersModel", b =>
                {
                    b.Property<string>("TrainerId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DogName");

                    b.Property<int>("DogNumber");

                    b.Property<string>("TrainerArea");

                    b.Property<string>("TrainerName");

                    b.HasKey("TrainerId");

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("LuckyPaw.Models.TrainingDogModel", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DogName");

                    b.Property<DateTime>("GraduationDate");

                    b.Property<string>("TrainerId");

                    b.Property<string>("TrainingType");

                    b.HasKey("TrainingId");

                    b.ToTable("TrainingDog");
                });

            modelBuilder.Entity("LuckyPaw.Models.TrainingServicesPriceModel", b =>
                {
                    b.Property<int>("TrainingServicesPriceID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("PriceTraining");

                    b.Property<string>("TrainingDesc");

                    b.Property<string>("TrainingName");

                    b.Property<int>("TrainingQty");

                    b.HasKey("TrainingServicesPriceID");

                    b.ToTable("TrainingServicesPrice");
                });
#pragma warning restore 612, 618
        }
    }
}
